name: Scrape Banks

on:
  schedule:
    - cron: '0 4,9 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run scrape script
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          urls=(
            "https://test-vercel-nextjs-storyblok-projec.vercel.app/scrape?bank=bri.co.id&secret=$CRON_SECRET"
            "https://test-vercel-nextjs-storyblok-projec.vercel.app/scrape?bank=bankmega.com&secret=$CRON_SECRET"
            "https://test-vercel-nextjs-storyblok-projec.vercel.app/scrape?bank=bca.co.id&secret=$CRON_SECRET"
            "https://test-vercel-nextjs-storyblok-projec.vercel.app/scrape?bank=bankbjb.co.id&secret=$CRON_SECRET"
            "https://test-vercel-nextjs-storyblok-projec.vercel.app/scrape?bank=bni.co.id&secret=$CRON_SECRET"
            "https://test-vercel-nextjs-storyblok-projec.vercel.app/scrape?bank=btn.co.id&secret=$CRON_SECRET"
            "https://test-vercel-nextjs-storyblok-projec.vercel.app/scrape?bank=cimbniaga.co.id&secret=$CRON_SECRET"
            "https://test-vercel-nextjs-storyblok-projec.vercel.app/scrape?bank=danamon.co.id&secret=$CRON_SECRET"
            "https://test-vercel-nextjs-storyblok-projec.vercel.app/scrape?bank=bankmandiri.co.id&secret=$CRON_SECRET"
            "https://test-vercel-nextjs-storyblok-projec.vercel.app/scrape?bank=maybank.co.id&secret=$CRON_SECRET"
            "https://test-vercel-nextjs-storyblok-projec.vercel.app/scrape?bank=ocbc.id&secret=$CRON_SECRET"
            "https://test-vercel-nextjs-storyblok-projec.vercel.app/scrape?bank=permatabank.com&secret=$CRON_SECRET"
            "https://test-vercel-nextjs-storyblok-projec.vercel.app/scrape?bank=panin.co.id&secret=$CRON_SECRET"
            "https://test-vercel-nextjs-storyblok-projec.vercel.app/scrape?bank=hsbc.co.id&secret=$CRON_SECRET"
            "https://test-vercel-nextjs-storyblok-projec.vercel.app/scrape?bank=dbs.id&secret=$CRON_SECRET"
            "https://test-vercel-nextjs-storyblok-projec.vercel.app/scrape?bank=uob.co.id&secret=$CRON_SECRET"
            "https://test-vercel-nextjs-storyblok-projec.vercel.app/scrape?bank=bi.go.id&secret=$CRON_SECRET"
          )

          for url in "${urls[@]}"; do
            echo "Fetching $url"
            curl -s "$url" > /dev/null
            sleep 60
          done
